site_name: Chen's LMS
repo_url: https://github.com/laozhou-in-germany/Chens_LMS_Public_CN/
edit_uri: blob/main/docs/docs/

nav:
    - 简介: index.md
    - 快速开始: quick_start.md
    - 示例展示: showcase.md
    - 帮助文档: reference.md
    - 关于: about.md
    - English:  en_cn.md



markdown_extensions:
  - footnotes