site_name: Chen's LMS
repo_url: https://github.com/laozhou-in-germany/Chens_LMS_Public_CN/
edit_uri: blob/main/docs/docs/

nav:
    - 快速开始:
        - 用户界面: qs01_ui.md
        - 使用目标管理: qs11_use_goal_management.md
        - 使用日志: qs12_use_journal.md
        - 使用知识管理: qs13_use_knowledge_management.md
        - 使用定期回顾: qs14_use_periodic_review.md
    - 展示案例:
        - 目标管理: sc_goal_management.md
        - 日志: sc_journal.md
        - 知识管理: sc_knowledge_management.md
        - 定期回顾: sc_periodic_review.md
    - 帮助手册: ref0_general.md
    - 关于: about.md
    - English:  en_cn.md
markdown_extensions:
  - footnotes
  - admonition